### ISSUE TITLE
SSE4A

### ISSUE THREAD

**Issue by Anbima** [Alex313031/thorium-legacy#90]
Hello,

I have the following processor:
AMD Phenom II X4 945

CPU-Z shows me the following:
SSE, SSE2, SSE3, SSE4A

Should I use SSE3 or SSE4?

**Comment by Alex313031** [comment]
@Anbima You have a member of the "Barcelona" CPUs. SSE4 actually comprises three seperate SIMD instruction classes:

SSE4A
SSE4.1
SSE4.2

Thorium SSE4 builds target SSE4.1 for the best of both worlds. The only CPUs that have SSE4.2 but not AVX are 1st gen core. Most SSE4 capable CPUs support SSE4.1. This includes Core 2 Duo.

Unfortunately, the Barcelona class is one exception, only supporting SSE4a (and is the only CPU family to do so). So for you, use the SSE3 releases.

But also don't worry, as it is unlikely that running a release compiled for SSE4a would show any noticeable performance improvement, especially since SSE4a only comprises two instructions > https://en.wikipedia.org/wiki/SSE4#SSE4a
